"""
Phase 8 — the controlled test-action executor.

WHY (SECURITY):
    Nothing generated by an LLM is ever executed as code. The executor walks
    a closed list of `TestAction`s, validates each one's typed parameters,
    and dispatches it to a dedicated handler that only touches existing
    building blocks:
        SET_TEMPERATURE        -> deterministic set-point            (Phase 2)
        SET_SENSOR_STATUS      -> TemperatureSensorSimulator.go_*    (Phase 2)
        READ_SENSOR            -> TemperatureSensorSimulator.tick()  (Phase 2)
        INJECT_FAULT/CLEAR_FAULT -> FaultRegistry.make_fault + FaultInjector (Phase 4)
        MQTT_*                 -> MqttConnection + Phase 3 wire helpers (Phase 3)
    READING faults are applied on the next READ through the existing Phase 4
    `FaultInjectedSimulator` adapter (shared decision engine, no duplication).

WHAT:
    `execute(actions, test_case_id, requirement_id)` runs the validated actions
    sequentially under a bounded wall-clock budget, collects per-step
    `StepEvidence`, and returns one aggregated `ExecutionResult`. FAIL
    (assertion evaluated, expectation not met) is always distinct from ERROR
    (execution could not complete).

HOW (determinism):
    The simulator is Phase 2's seeded `TemperatureSensorSimulator`: same seed +
    same tick sequence => same readings. A controlled set-point (SET_TEMPERATURE)
    makes the device report exactly the commanded value on subsequent READs
    until it is changed, faulted, cleared, or reset. ASSERT_* steps are pure
    evaluations (app/testing/assertions.py) of the actually-observed value —
    never fabricated.

HOW TO VERIFY:
    See tests/unit/test_execution_executor.py and
    tests/integration/test_execution_full_chain.py.
"""

from __future__ import annotations

import math
import time
from datetime import datetime, timezone

from loguru import logger

from app.config import Settings
from app.faults.engine import FaultInjector
from app.faults.models import (
    FaultImpact,
    FaultParams,
    FaultSeverity,
    InjectionCondition,
)
from app.faults.registry import make_fault
from app.faults.simulator_adapter import FaultInjectedSimulator
from app.iot.mqtt_messages import reading_to_mqtt_message, serialize_message
from app.iot.models import SensorReading, SensorStatus
from app.iot.simulator import TemperatureSensorSimulator
from app.testing import assertions
from app.testing.actions import TestAction, TestActionType, validate_action
from app.testing.errors import (
    ExecutionTimeoutError,
    FaultUnavailableError,
    InvalidActionParameterError,
    MqttUnavailableError,
    SimulatorUnavailableError,
    UnknownActionError,
)
from app.testing.models import (
    EnvironmentSnapshot,
    ExecutionResult,
    MqttSnapshot,
    SensorMqttView,
    SimulatorStateSnapshot,
    StepEvidence,
    StepOutcome,
    TestStatus,
)


def _fmt_value(value) -> str:
    if isinstance(value, float):
        if math.isnan(value):
            return "no value (offline)"
        return f"{value:g}"
    return "" if value is None else str(value)


class TestExecutor:
    """Executes validated `TestAction`s against the simulated IoT environment."""

    def __init__(
        self,
        *,
        simulator: TemperatureSensorSimulator | None = None,
        injector: FaultInjector | None = None,
        mqtt_connection=None,
        settings_: Settings | None = None,
        max_duration_seconds: float | None = None,
        max_wait_seconds: float | None = None,
    ):
        from app.config import settings as _singleton

        self._settings = settings_ if settings_ is not None else _singleton
        self.simulator = simulator
        self.injector = injector if injector is not None else FaultInjector()
        self._mqtt_connection = mqtt_connection
        self.max_duration_seconds = (
            max_duration_seconds
            if max_duration_seconds is not None
            else self._settings.execution_max_duration_seconds
        )
        self.max_wait_seconds = (
            max_wait_seconds
            if max_wait_seconds is not None
            else self._settings.execution_max_wait_seconds
        )

        # per-run device state
        self._command: float | None = None
        self._last_reading: SensorReading | None = None
        self._subscriber = None
        self._active_topics: list[str] = []

    # ------------------------------------------------------------------ public

    def execute(
        self,
        actions: list[TestAction],
        *,
        test_case_id: str = "MANUAL",
        requirement_id: str = "NONE",
    ) -> ExecutionResult:
        """Execute a validated action list sequentially under the budget."""
        if not actions:
            raise UnknownActionError("execution requires at least one action")

        started_at = datetime.now(timezone.utc)
        wall_start = time.monotonic()
        evidence: list[StepEvidence] = []

        try:
            for index, action in enumerate(actions, start=1):
                if time.monotonic() - wall_start >= self.max_duration_seconds:
                    raise ExecutionTimeoutError(
                        f"test exceeded the {self.max_duration_seconds:g}s wall-clock budget"
                    )
                evidence.append(self._execute_one(index, action))
        except Exception as exc:  # noqa: BLE001 - capture ANY execution fault
            if isinstance(exc, ExecutionTimeoutError):
                error = str(exc)
            else:
                error = f"{type(exc).__name__}: {exc}"
            evidence.append(
                StepEvidence(
                    step_number=len(evidence) + 1,
                    action="EXECUTION_ABORTED",
                    action_result=StepOutcome.ERROR,
                    error_message=error,
                    timestamp=datetime.now(timezone.utc),
                    duration=time.monotonic() - wall_start,
                )
            )
            return self._build_result(
                start=started_at,
                wall_start=wall_start,
                evidence=evidence,
                status=TestStatus.ERROR,
                failure_reason=None,
                error_message=error,
                test_case_id=test_case_id,
                requirement_id=requirement_id,
            )

        status, reason, error = _aggregate_status(evidence)
        return self._build_result(
            start=started_at,
            wall_start=wall_start,
            evidence=evidence,
            status=status,
            failure_reason=reason,
            error_message=error,
            test_case_id=test_case_id,
            requirement_id=requirement_id,
        )

    # ----------------------------------------------------------- per-step logic

    def _execute_one(self, step_number: int, action: TestAction) -> StepEvidence:
        step_started = datetime.now(timezone.utc)
        step_wall = time.monotonic()
        try:
            outcome = self._dispatch(action)
        except ExecutionTimeoutError:
            raise
        except (InvalidActionParameterError, SimulatorUnavailableError,
                MqttUnavailableError, FaultUnavailableError, UnknownActionError) as exc:
            return StepEvidence(
                step_number=step_number,
                action=action.action.value,
                action_result=StepOutcome.ERROR,
                error_message=str(exc),
                timestamp=step_started,
                duration=time.monotonic() - step_wall,
            )
        except Exception as exc:  # noqa: BLE001 - safety net
            logger.debug(f"Unhandled execution fault on {action.action.value}: {exc}")
            return StepEvidence(
                step_number=step_number,
                action=action.action.value,
                action_result=StepOutcome.ERROR,
                observed=str(exc),
                error_message=f"unexpected fault: {type(exc).__name__}: {exc}",
                timestamp=step_started,
                duration=time.monotonic() - step_wall,
            )

        assertion = outcome.get("assertion")
        if isinstance(assertion, assertions.AssertionResult):
            assertion_result = (
                TestStatus.PASS if assertion.passed else TestStatus.FAIL
            )
        else:
            assertion_result = None

        return StepEvidence(
            step_number=step_number,
            action=action.action.value,
            action_result=outcome["outcome"],
            assertion_result=assertion_result,
            expected=_fmt_value(outcome.get("expected")),
            observed=_fmt_value(outcome.get("observed")),
            failure_reason=outcome.get("reason"),
            error_message=outcome.get("error"),
            timestamp=step_started,
            duration=time.monotonic() - step_wall,
        )

    # ----------------------------------------------------------------- dispatch

    def _dispatch(self, action: TestAction) -> dict:
        if action.action is TestActionType.SET_SENSOR_STATUS:
            params = validate_action(action)
            self._require_simulator()
            if params.status is SensorStatus.OFFLINE:
                self.simulator.go_offline()
            else:
                self.simulator.go_online()
            return {"outcome": StepOutcome.OK, "expected": params.status.value,
                    "observed": self.simulator.status.value}

        if action.action is TestActionType.SET_TEMPERATURE:
            params = validate_action(action)
            self._require_simulator()
            value = float(params.value_c)
            if not math.isfinite(value):
                raise InvalidActionParameterError(
                    f"SET_TEMPERATURE requires a finite value, got {params.value_c!r}"
                )
            self._command = value
            return {"outcome": StepOutcome.OK, "expected": _fmt_value(value),
                    "observed": "commanded"}

        if action.action is TestActionType.READ_SENSOR:
            validate_action(action)
            reading = self._read_reading()
            return {
                "outcome": StepOutcome.OK,
                "expected": "a reading from the device",
                "observed": (
                    "offline" if reading.status is SensorStatus.OFFLINE
                    else _fmt_value(reading.value_c)
                ),
            }

        if action.action is TestActionType.WAIT:
            params = validate_action(action)
            if params.seconds > self.max_wait_seconds:
                raise InvalidActionParameterError(
                    f"WAIT of {params.seconds:g}s exceeds the configured cap of "
                    f"{self.max_wait_seconds:g}s"
                )
            time.sleep(params.seconds)
            return {"outcome": StepOutcome.OK,
                    "expected": f"hold {params.seconds:g}s",
                    "observed": f"held {params.seconds:g}s"}

        if action.action is TestActionType.RESET_SIMULATOR:
            validate_action(action)
            self._require_simulator()
            self.simulator.reset()
            self._command = None
            self._last_reading = None
            if self._subscriber is not None:
                self._subscriber.clear()
            return {"outcome": StepOutcome.OK, "expected": "device reset",
                    "observed": "reset to tick 0"}

        if action.action is TestActionType.MQTT_SUBSCRIBE:
            params = validate_action(action)
            conn = self._ensure_mqtt()
            if params.topics:
                topics = list(params.topics)
            elif params.topic:
                topics = [params.topic]
            else:
                topics = [
                    self._settings.mqtt_topic_temperature,
                    self._settings.mqtt_topic_status,
                ]
            from app.iot.mqtt_subscriber import SensorMqttSubscriber

            self._subscriber = SensorMqttSubscriber(conn, topics=topics)
            self._subscriber.subscribe_all()
            self._active_topics = topics
            return {"outcome": StepOutcome.OK,
                    "expected": f"subscribe {topics}",
                    "observed": "subscribed"}

        if action.action is TestActionType.MQTT_PUBLISH:
            params = validate_action(action)
            conn = self._ensure_mqtt()
            active_transport = [
                s for s in self.injector.active_faults()
                if s.expected_detection.impacted_subsystem
                in (FaultImpact.MESSAGE, FaultImpact.CONNECTION)
            ]
            if active_transport and params.payload is None:
                return {
                    "outcome": StepOutcome.SKIPPED,
                    "expected": "a published message",
                    "reason": (
                        "active transport fault(s) "
                        f"{[s.fault_type.value for s in active_transport]} require the "
                        "Phase 4 FaultInjectingPublisher pipeline, which Phase 8's raw "
                        "MQTT_PUBLISH does not apply"
                    ),
                }
            topic = params.topic or self._settings.mqtt_topic_temperature
            if params.payload is not None:
                raw: bytes = params.payload.encode("utf-8")
            else:
                reading = self._last_reading
                if reading is None:
                    self._require_simulator()
                    reading = self._read_reading()
                message = reading_to_mqtt_message(self._sensor_id(), reading)
                raw = serialize_message(message).encode("utf-8")
            ok = conn.publish(topic, raw, qos=params.qos)
            if not ok:
                raise MqttUnavailableError(f"broker did not accept publish to '{topic}'")
            return {"outcome": StepOutcome.OK,
                    "expected": f"publish to {topic}",
                    "observed": "published"}

        if action.action is TestActionType.INJECT_FAULT:
            params = validate_action(action)
            fault = self._build_fault_spec(params)
            try:
                fault_id = self.injector.inject(fault)
            except Exception as exc:
                raise FaultUnavailableError(
                    f"could not inject {params.fault_type.value}: {exc}"
                ) from exc
            return {"outcome": StepOutcome.OK,
                    "expected": f"inject {params.fault_type.value}",
                    "observed": f"active fault_id={fault_id}"}

        if action.action is TestActionType.CLEAR_FAULT:
            params = validate_action(action)
            if params.fault_id is not None:
                try:
                    self.injector.deactivate(params.fault_id)
                except Exception as exc:
                    raise FaultUnavailableError(str(exc)) from exc
            else:
                for spec in self.injector.active_faults():
                    self.injector.deactivate(spec.fault_id)
            return {"outcome": StepOutcome.OK,
                    "expected": "clear active faults",
                    "observed": "faults cleared"}

        if action.action is TestActionType.ASSERT_VALUE:
            params = validate_action(action)
            observed = None if self._last_reading is None else self._last_reading.value_c
            result = assertions.evaluate_value(observed, params.value, params.tolerance)
            return self._assertion_outcome(result)

        if action.action is TestActionType.ASSERT_RANGE:
            params = validate_action(action)
            self._require_simulator()
            low = params.low if params.low is not None else self.simulator.config.min_temperature_c
            high = params.high if params.high is not None else self.simulator.config.max_temperature_c
            observed = None if self._last_reading is None else self._last_reading.value_c
            result = assertions.evaluate_range(observed, low, high)
            return self._assertion_outcome(result)

        if action.action is TestActionType.ASSERT_STATUS:
            params = validate_action(action)
            if self._last_reading is not None:
                status, valid = self._last_reading.status, self._last_reading.valid
            elif self.simulator is not None:
                status, valid = self.simulator.status, None
            else:
                status, valid = None, None
            result = assertions.evaluate_status(
                status, valid,
                expected_status=params.status,
                expected_valid=params.valid,
            )
            return self._assertion_outcome(result)

        if action.action is TestActionType.ASSERT_MESSAGE:
            params = validate_action(action)
            if self._subscriber is None:
                return {
                    "outcome": StepOutcome.SKIPPED,
                    "expected": f">={params.min_count} message(s)",
                    "reason": "no MQTT subscriber is active for this test",
                }
            bounded = min(params.wait_seconds, self.max_wait_seconds)
            self._subscriber.wait_for_messages(count=params.min_count, timeout=bounded)
            received = list(self._subscriber.received_messages)
            result = assertions.evaluate_message(
                received,
                topic=params.topic,
                field=params.field,
                equals=params.equals,
                min_count=params.min_count,
            )
            return self._assertion_outcome(
                result,
                observed_summary=(
                    f"{len(received)} validated message(s), "
                    f"{len(self._subscriber.invalid_messages)} invalid"
                ),
            )

        raise UnknownActionError(f"no handler for action type {action.action}")

    # ------------------------------------------------------------------ helpers

    @staticmethod
    def _assertion_outcome(result, observed_summary: str | None = None) -> dict:
        return {
            "outcome": StepOutcome.OK,
            "assertion": result,
            "expected": result.expected,
            "observed": observed_summary if observed_summary is not None else result.observed,
            "reason": None if result.passed else result.detail,
        }

    def _read_reading(self) -> SensorReading:
        self._require_simulator()
        # Phase 4 READING faults take precedence (shared decision engine).
        if self.injector is not None:
            index = self.simulator.tick_count
            if self.injector.sensor_fault_at(index) is not None:
                reading = FaultInjectedSimulator(self.simulator, self.injector).tick()
                self._last_reading = reading
                return reading
        raw = self.simulator.tick()
        if self._command is not None and raw.status is SensorStatus.ONLINE:
            cfg = self.simulator.config
            valid = cfg.min_temperature_c <= self._command <= cfg.max_temperature_c
            reading = SensorReading(
                tick=raw.tick,
                timestamp=raw.timestamp,
                value_c=self._command,
                unit=raw.unit,
                status=raw.status,
                valid=valid,
            )
            self._last_reading = reading
            return reading
        self._last_reading = raw
        return raw

    def _sensor_id(self) -> str:
        if self.simulator is not None:
            return self.simulator.config.device_name
        return "temperature-sensor"

    @staticmethod
    def _build_fault_spec(params):
        fault_params = FaultParams(
            overshoot_c=params.overshoot_c,
            undershoot_c=params.undershoot_c,
            invalid_data_kind=params.invalid_data_kind,
            delay_seconds=params.delay_seconds,
            duplicate_count=params.duplicate_count,
            invalid_payload_kind=params.invalid_payload_kind,
        )
        condition = InjectionCondition(
            start_tick=params.start_tick,
            end_tick=params.end_tick,
            every_n=params.every_n,
        )
        kwargs: dict = {"params": fault_params, "injection_condition": condition}
        if params.severity is not None:
            try:
                kwargs["severity"] = FaultSeverity(params.severity)
            except ValueError as exc:
                raise InvalidActionParameterError(
                    f"unknown fault severity {params.severity!r}"
                ) from exc
        return make_fault(params.fault_type, **kwargs)

    def _require_simulator(self) -> None:
        if self.simulator is None:
            raise SimulatorUnavailableError(
                "no simulator configured; cannot run device actions"
            )

    def _ensure_mqtt(self):
        """Return a connected MQTT connection, creating/connecting lazily.

        Never pretends a broker is available: a failed connect raises
        `MqttUnavailableError` (the service may map it to an honest SKIPPED).
        """
        from app.iot.mqtt_client import MqttConnection

        if self._mqtt_connection is None:
            self._mqtt_connection = MqttConnection(
                host=self._settings.mqtt_broker_host,
                port=self._settings.mqtt_broker_port,
                client_id=self._settings.mqtt_client_id,
            )
        if not self._mqtt_connection.is_connected:
            try:
                self._mqtt_connection.connect()
            except Exception as exc:
                raise MqttUnavailableError(
                    f"MQTT broker at {self._settings.mqtt_broker_host}:"
                    f"{self._settings.mqtt_broker_port} is unavailable: {exc}"
                ) from exc
        return self._mqtt_connection

    def _disconnect_mqtt(self) -> None:
        """Close a used MQTT connection gracefully (no stray network threads)."""
        if self._mqtt_connection is not None:
            try:
                self._mqtt_connection.disconnect()
            except Exception:  # noqa: BLE001 - cleanup must never mask a result
                pass

    # ---------------------------------------------------------------- snapshots

    def _build_result(
        self, *, start, wall_start, evidence, status, failure_reason, error_message,
        test_case_id: str, requirement_id: str,
    ) -> ExecutionResult:
        completed = datetime.now(timezone.utc)
        sim_state = SimulatorStateSnapshot(
            device_name=(self.simulator.config.device_name if self.simulator else "no-simulator"),
            status=(self.simulator.status if self.simulator else None),
            tick_count=(self.simulator.tick_count if self.simulator else 0),
            min_temperature_c=(self.simulator.config.min_temperature_c if self.simulator else 0.0),
            max_temperature_c=(self.simulator.config.max_temperature_c if self.simulator else 0.0),
            accuracy_c=(self.simulator.config.accuracy_c if self.simulator else 0.0),
            commanded_value=self._command,
            last_observed_value=(self._last_reading.value_c if self._last_reading else None),
            seed=(self.simulator.config.seed if self.simulator else 0),
        )
        mqtt = self._mqtt_snapshot()
        self._disconnect_mqtt()
        env = EnvironmentSnapshot(
            app_env=self._settings.app_env,
            llm_provider=self._settings.llm_provider,
            execution_max_duration_seconds=self.max_duration_seconds,
            execution_max_wait_seconds=self.max_wait_seconds,
            mqtt_broker=f"{self._settings.mqtt_broker_host}:{self._settings.mqtt_broker_port}",
        )
        steps_passed = sum(1 for e in evidence if e.passed)
        steps_failed = sum(
            1 for e in evidence
            if e.assertion_result is TestStatus.FAIL or e.action_result is StepOutcome.FAIL
        )

        observed_values: dict[str, str] = {}
        if self._last_reading is not None:
            observed_values["temperature"] = _fmt_value(self._last_reading.value_c)
            observed_values["status"] = self._last_reading.status.value
            observed_values["valid"] = str(self._last_reading.valid)
        if self._command is not None:
            observed_values["commanded"] = _fmt_value(self._command)

        return ExecutionResult(
            test_case_id=test_case_id,
            requirement_id=requirement_id,
            status=status,
            started_at=start,
            completed_at=completed,
            duration=time.monotonic() - wall_start,
            steps_executed=len(evidence),
            steps_passed=steps_passed,
            steps_failed=steps_failed,
            observed_values=observed_values,
            expected_values={},
            failure_reason=failure_reason,
            error_message=error_message,
            execution_evidence=evidence,
            environment=env,
            simulator_state=sim_state,
            mqtt_information=mqtt,
        )

    def _mqtt_snapshot(self) -> MqttSnapshot | None:
        conn = self._mqtt_connection
        if conn is None and self._subscriber is None:
            return None
        received = list(self._subscriber.received_messages) if self._subscriber else []
        invalid = list(self._subscriber.invalid_messages) if self._subscriber else []
        view = None
        if received:
            last = received[-1]
            view = SensorMqttView(
                sensor_id=last.sensor_id,
                temperature=last.temperature,
                status=last.status,
                valid=last.valid,
            )
        return MqttSnapshot(
            available=bool(conn and conn.is_connected),
            connected=bool(conn and conn.is_connected),
            broker=f"{self._settings.mqtt_broker_host}:{self._settings.mqtt_broker_port}",
            topic=self._active_topics[0] if self._active_topics else None,
            received_count=len(received),
            invalid_count=len(invalid),
            last_received=view,
        )


def _aggregate_status(evidence: list[StepEvidence]) -> tuple[TestStatus, str | None, str | None]:
    """Aggregate step evidence into one final status (ERROR > SKIPPED > FAIL > PASS)."""
    for e in evidence:
        if e.action_result is StepOutcome.ERROR:
            return TestStatus.ERROR, None, e.error_message or "an execution step failed"
    for e in evidence:
        if e.action_result is StepOutcome.SKIPPED:
            return TestStatus.SKIPPED, e.failure_reason or "a step was skipped", None
    for e in evidence:
        if e.assertion_result is TestStatus.FAIL or e.action_result is StepOutcome.FAIL:
            return TestStatus.FAIL, e.failure_reason or "an assertion was not satisfied", None
    return TestStatus.PASS, None, None